apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileBinding
metadata:
  namespace: nginx-deploy
  name: nginx-binding
spec:
  profileRef:
    kind: SelinuxProfile 
    name: nginx-secure-recorded
  image: nginxinc/nginx-unprivileged:1.21